name: Continuous Integration


on:
  pull_request:
    branches:
      - main
    paths:
      - "config/**/*.tf"
      - "Makefile"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


env:
  TERRAFORM_VERSION_CLI: "1.0.10"


jobs:

  check:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: "Clone current repository"
        uses: actions/checkout@v3
      - name: "Set up Terraform CLI"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${TERRAFORM_VERSION_CLI}
      - name: "Check format"
        run: make check

  validate:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: "Clone current repository"
        uses: actions/checkout@v3
      - name: "Set up Terraform CLI"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${TERRAFORM_VERSION_CLI}
      - name: "Validate syntax"
        run: make validate
